language: scala

branches:
  only:
    - master

script:
  - sbt clean coverage sclinterJVM/test sclinterJVM/coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "Sujeet Kausallya Gholap"
  - git config --local user.email "sujeetgholap+travis@gmail.com"
  - git tag "$(bash get-version.sh)"
  # `clean` to remove the profiling overhead added to the
  # classes for generating the coverage info during test
  - sbt clean sclinterJVM/assembly sclinterJS/fullOptJS
  - cp jvm/target/scala-2.12/sclinter.jar ./
  - cp js/target/scala-2.12/sclinter-opt.js ./sclinter.js
  - zip -r sclinter.zip sclinter.jar sclinter.js lint

deploy:
  provider: releases
  skip_cleanup: true
  overwrite: true
  file: sclinter.zip
  api_key:
    secure:
      "DIW1niVftSbZVD9lbZNOIlNqlQIrX+x1k5cBSIwfTWGJBQYpIcxS56d3\
       1ptQ0Ed5SGngSbC0nzOcbjN4BVLgseEpDssZbQBBtzkisGT5R+YCDLTm\
       WS6WfkLqv56HbHhISVo0oS0eGQDIqWWiDPBBt1XDVIq/ReQubf/HtbIP\
       VcjHoDZAEt37055o//QyRs8it5KcZsOvrmI0TPHNMk3uG2uysvDx+E+N\
       prKDPmVssQlqUckjdjdjvLmdC4mwiL4O/lkK9L3zzbEl404mXINbIGbZ\
       zzGnsNmPAEKp7VXP6NxuBqFWRbaFI6dXCTALyG4dh08QWitI7YJPXbVL\
       nsTh9NM82QNtnVKNhbJPjFgDOEyKJh63DC741VjZwfp7z20bp4pGMJzC\
       VGRpkYUHeZ+q/gdH5NW3U5s8Gyd1PS7KckshfdIt8EBeztsKc6YeynBO\
       nuckR49QHgIIJcViqPJPRD8rFuB5PjLOE0mHZKUbJGa1WQRbYwDBLQyy\
       zg4C4omXjwoo411arE1DUPv6LqIhcM2WJlRf0PsbA84MRtjoV3GT9ZO9\
       uBp1tTIMz7bK0Wkn1bCjnoo/mFArU25B15h2QoC71UVCyjDhl86eRs+k\
       8e/pe7E03iUJ0KqD6l4tkpqXkdUjrWegcv2h4N26bMO3j1S80ecwSyCI\
       JqwWpWZFm8k="
  on:
    repo: scaledata/sclinter
    condition: '"$(git tag -l $(bash get-version.sh)" = ""'
